name: HeatCluster Build

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag for Docker image"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          quay.io login -u $QUAY_USER -p $QUAY_PASSWORD

      - name: Docker Build
        run: |
          docker build -t 'heatcluster:test' .

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to <insert repo>
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          build-args: HEATCLUSTER_VER=${{ github.event.inputs.version }}
          push: true
          target: app
          tags: heatcluster:${{ github.event.inputs.version }}

      - name: L
      - name: Build and push latest tag to Quay
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          build-args: HEATCLUSTER_VER=${{ github.event.inputs.version }}
          push: true
          target: app
          tags: heatcluster:latest   
