name: Check versions

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * TUE'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout
        
      - name: versions
        run: |
          issue_text="Needing updates:  "     
          stevebsdocker_containers=($(grep -h container modules/* | grep stevebsdocker | sort | uniq | grep -v latest | awk '{print $2}' | sed 's/'\''//g'))
          for container in ${stevebsdocker_containers[@]}
          do
            base=$(echo $container | cut -f 1 -d ":")
            repo_version=$(echo $container | cut -f 2 -d ":")
            
            docker pull $base:latest
            latest_version=$(docker inspect --format '{{ index .Config.Labels "software.version"}}' $base:latest)
            
            if [[ "$latest_version" == "$repo_version" ]]
            then
              echo "No version change for $base:$repo_version" | tee -a versions.txt
            else
              echo "New version for $base! Upgrade to $latest_version from $repo_version." | tee -a versions.txt
              issue_text="$issue_text<br>- $base from $repo_version to $latest_version  "
            fi
          done
          echo $issue_text
          cat versions.txt
          echo 'ISSUE_TEXT='$issue_text >> $GITHUB_ENV
